- name: Deploy Redmine application
  hosts: all
  become: true
  roles:
    - geerlingguy.pip

  tasks:

    - name: Create directory for Redmine
      file:
        path: /opt/redmine
        state: directory
        mode: '0755'

    - name: Create .env file from template
      template:
        src: templates/.env.j2
        dest: /opt/redmine/.env
        mode: '0644'

    - name: Copy docker-compose.yml file
      copy:
        src: redmine-docker-compose.yml
        dest: /opt/redmine/docker-compose.yml
        mode: '0755'

    - name: Register docker-compose file
      command: docker compose -f /opt/redmine/docker-compose.yml config
      args:
        chdir: /opt/redmine
      register: validate_compose
      changed_when: false

    - name: Debug docker-compose file
      debug:
        var: validate_compose

    - name: Start Redmine application
      community.docker.docker_compose:
        project_src: /opt/redmine
        state: present
      tags:
        - start

    - name: Confirm application is running
      command: docker ps
      register: running_containers
      changed_when: false
      tags: debug

    - name: Debug running containers
      debug:
        msg: "{{ running_containers.stdout }}"
      tags: debug

  vars:
    datadog_api_key: "{{ DATADOG_API_KEY }}"
    datadog_site: "{{ DATADOG_SITE }}"

- name: Install and configure Datadog agent
  hosts: webservers
  become: true

  tasks:

    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent

    - name: Configure http_check in Datadog
      ansible.builtin.copy:
        dest: "/etc/datadog-agent/conf.d/http_check.d/conf.yaml"
        content: |
          http_check:
            url: "{{ DATADOG_HTTP_CHECK_URL }}"
            name: "Redmine Application Health"
        mode: '0755'
