- name: Deploy Redmine application
  hosts: all
  become: true
  roles:
    - geerlingguy.pip

  tasks:
    - name: Create directory for Redmine
      file:
        path: /opt/redmine
        state: directory
        mode: '0755'
    
    - name: Create .env file from template
      template:
        src: templates/.env.j2
        dest: '.env'
        mode: '0644'

    - name: Verify .env file exists
      stat:
        path: .env
      register: env_file_check

    - name: Debug .env file
      debug:
        msg: "File exists: {{ env_file_check.stat.exists }}"

    - name: Verify contents of .env file
      ansible.builtin.command: cat .env
      register: env_file_content

    - name: Debug .env contents
      debug:
        msg: "{{ env_file_content.stdout }}"

    - name: Start container
      community.docker.docker_container:
        name: redmine_container
        image: redmine:5.0
        ports:
          - 80:3000
        env_file:
          - .env
        output_logs: true

    - name: Confirm application is running
      command: docker ps
      register: running_containers
      changed_when: false
      tags: debug

    - name: Debug running containers
      debug:
        msg: "{{ running_containers.stdout }}"
      tags: debug

  vars:
    datadog_api_key: "{{ DATADOG_API_KEY }}"
    datadog_site: "{{ DATADOG_SITE }}"

- name: Install and configure Datadog agent
  hosts: webservers
  become: true

  tasks:

    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent

    - name: Configure http_check in Datadog
      ansible.builtin.copy:
        dest: "/etc/datadog-agent/conf.d/http_check.d/conf.yaml"
        content: |
          http_check:
            url: "{{ DATADOG_HTTP_CHECK_URL }}"
            name: "Redmine Application Health"
        mode: '0755'
