
- name: Install and configure Datadog agent
  hosts: webservers
  become: true

  tasks:

    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent

    - name: Configure http_check in Datadog
      ansible.builtin.copy:
        dest: "/etc/datadog-agent/conf.d/http_check.d/conf.yaml"
        content: |
          http_check:
            url: "{{ dd_checks.http_check.url }}"
            name: "Redmine Application Health"
