- name:  Install Docker
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
        state: latest

    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to Apt sources
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        create: yes

    - name: Update apt cache again
      apt:
        update_cache: true

    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
      register: docker_install

    - name: Check if Docker is installed
      command: docker -v
      register: docker_version
      changed_when: false
      failed_when: docker_version.rc != 0

    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

# Команды для установки вручную:
# apt remove --purge docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
# apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
