- name:  Install Docker
  hosts: all
  become: true

  tasks:
    - name: Install Docker and Docker Compose plugin
      apt:
        name:
          - docker.io
          - docker-compose-plugin
        state: latest
        update_cache: true
